### ISSUE TITLE
Full popup blocker?

### ISSUE THREAD

**Issue by Madis0** [ivanruvalcaba/BehindTheOverlayRevival#3]
Hello,
Do you have any plans for creating a full modal popup blocker, as an optional feature for this extension or a similar new one?

By full, I mean:

- Automatic blocking
- Blocked count
- Unblocking, if that's possible (maybe hide instead of removing or just attempt to recreate if removed)

There are [extensions](https://chrome.google.com/webstore/detail/auto-overlay-remover/kefcbonbdcahbihclibfdeeddceiabjm) [like this](https://chrome.google.com/webstore/detail/overlay-blocker/inncfpkneoefpgnoggjhcnkjhbcdeimo) [for Chrome](https://chrome.google.com/webstore/detail/pop-up-blocker-for-chrome/bkkbcggnhapdmkeljlodobbkopceiche) but I think Firefox has also a big need for one.

Edit: noticed "Add site whitelist/blacklist support (on user demand)." in front page; if it is what I'm describing, I'm glad you already consider it!

**Comment by ivanruvalcaba** [comment]
I have thought for a while in this functionality, but honestly, I do not want the extension to be intrusive for the user, that is, I want it to be as simple as possible for usability issues.

Maybe in the future, I can implement it.

Best regards.
