### ISSUE TITLE
Please make context menu optional

### ISSUE THREAD

**Issue by FL-KJ** [ivanruvalcaba/BehindTheOverlayRevival#5]
Basically what the title says. In my opinion this plug-in shoots itself in the foot by not making this an optional setting; there's no need to clutter the context menu with an unremovable item, especially when it adds a button to the toolbar anyway.

**Comment by ivanruvalcaba** [comment]
Well, I reimplemented the _Behind The Overlay Revival_ functionality, so now there is no need to use a context menu.

I'll close the thread.

Best regards.
