### ISSUE TITLE
0.1.8 not working at all

### ISSUE THREAD

**Issue by siffegh** [ivanruvalcaba/BehindTheOverlayRevival#6]
No icon, no context menu choice. FF v55, Nightly, and Waterfox.

**Comment by ivanruvalcaba** [comment]
The button has been moved to the address bar and replaced the one that was in the toolbar, as well as the context menu. The shortcut keys are still active (`Shit + Alt + X`), though. **The web extension is only enabled on web pages that use the HTTP/HTTPS protocol**.

Here's a screenshot:

https://github.com/ivanruvalcaba/BehindTheOverlayRevival/blob/master/docs/bor.jpg

I personally have tried it on Firefox 55.0.3 (stable), Firefox 56.0b6 (Developer/Beta) and Firefox Nightly (57.0a1) on Linux (64bits). Please check if this is correct if the problem persists do not hesitate to let me know!

Best regards.
